[tools]
"github:pesde-pkg/pesde" = "latest"
"github:luau-lang/lute" = "1.0.0"
"github:JohnnyMorganz/StyLua" = "2.5.2"
"github:JohnnyMorganz/luau-lsp" = "1.68.0"
"github:Kampfkarren/selene" = "0.31.0"
"npm:@changesets/cli" = "2.31.0"
